Revert k8s-eos to configmap

diff --git a/src/job/k8s-eos.yml b/src/job/k8s-eos.yml
--- a/src/job/k8s-eos.yml
+++ b/src/job/k8s-eos.yml
@@ -1,3 +1,33 @@
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: k8s-eos-script
+data:
+  script.sh: |
+    #!/bin/bash
+
+    sleep 15
+
+    ls_output=$(ls /eos 2>&1)
+    if [ $? -ne 0 ]; then
+      echo "error: $ls_output"
+      exit 1
+    fi
+
+    ls_output=$(ls /eos/user 2>&1)
+    if [ $? -ne 0 ]; then
+      echo "error: $ls_output"
+      exit 1
+    fi
+
+    n=$(ls /eos/user | wc  -l)
+    if [ $n -ne 26 ]; then
+      echo "error: wrong number of subdirectories in /eos/user, expected 26 but found ${n}"
+      exit 1
+    fi
+
+    echo "done"
+---
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -13,24 +43,23 @@ spec:
       securityContext:
         seLinuxOptions:
           type: "spc_t"
+      volumes:
+        - name: k8s-eos-script
+          configMap:
+            name: k8s-eos-script
+        - name: eos
+          hostPath:
+            path: /var/eos
       containers:
         - name: k8s-eos
           image: bash:5.0.17
           imagePullPolicy: IfNotPresent
           command:
-            - "/usr/local/bin/bash"
-            - "/mnt/gitlab-repo/src/script/k8s-eos.sh"
+            - /usr/local/bin/bash
+            - /tmp/script/script.sh
           volumeMounts:
-            - name: gitlab-repo
-              mountPath: /mnt/gitlab-repo
-              mountPropagation: HostToContainer
+            - name: k8s-eos-script
+              mountPath: /tmp/script
             - name: eos
               mountPath: /eos
               mountPropagation: HostToContainer
-      volumes:
-        - name: gitlab-repo
-          hostPath:
-            path: /mnt/gitlab-repo
-        - name: eos
-          hostPath:
-            path: /var/eos
